### ISSUE TITLE
Invalid Template URL

### ISSUE THREAD

**Issue by maplion** [galaxy4public/aws-cloudformation-badges#2]
First, thank you for doing this; finally, someone attempted to address this in a proper manner.

I had to change my URL for the TemplateURL to one of the s3 formats: https://<bucket name>.s3.<region>.amazonaws.com/badges.template

I also had to set the policies on the bucket to public, which should probably be mentioned in the README.  The steps included setting "Block Public Access" settings:

- Block public access to buckets and objects granted through new public bucket policies => Off
- Block public and cross-account access to buckets and objects through any public bucket policies => Off

Then adding a bucket policy.
Here's an example bucket policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<bucket name>/*"
        }
    ]
}
```

**Comment by galaxy4public** [comment]
TemplateURL for S3 is a result of a recent change by AWS.  The old scheme is supposed to be still supported for some time, but I agree, I need to update the README file with the recommended syntax.

As it comes to permissions, this is also a quite recent change by AWS when they introduced that "Block Public Access" in an attempt to handle all these organisations who do not have proper security controls on how they use S3.

I will address both your points once I fix other issues you raise.

Thanks for contributing!

**Comment by galaxy4public** [comment]
JFYI, I am not convinced that the S3 bucket policy is needed.  The stack sets the public access for the badge image explicitly during the upload.  Also, setting up a bucket policy would mean that any object inside the bucket is affected.  The current design exposes only objects explicitly created by the Lambda function.

**Comment by maplion** [comment]
Yes, for your template and generated content, you are correct.  To
reference the template from a bucket, however, then the template has to be
accessible, which is to what I was referring.  That may be obvious, but if
you're attempting to run it from something other than the CLI and using the
`TemplateURL:` option, then it has to be placed in an S3 bucket you have
access to GetObject -- I was just trying to further enhance/clarify your
README.

**Comment by galaxy4public** [comment]
@maplion, I think the permissions on the bucket holding the template are outside of the scope for this project.  The reason is that I cannot dictate what permissions should be there and there are multiple ways people can configure it: e.g. they can create a private bucket for storing templates, then introduce VPC endpoints for S3 and CloudFormation and this way CloudFormation will be able to read from the bucket.  There are just too many ways how this can be achieved, so I truly believe it is outside of the scope here.
